---
- name: Install Nginx on Amazon Linux
  hosts: web
  become: yes

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest
      become: yes

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      become: yes

    - name: Start Nginx and enable on boot
      systemd:
        name: nginx
        state: started
        enabled: yes

